account/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import DashboardView,UserRegistration,NewProfile,LoginView


app_name = 'account'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'),name='login'),
    path('logout/', LogoutView.as_view(),name='logout'),
    path('register/',UserRegistration.as_view() ,name='register'),
    path('dashboard/',DashboardView.as_view() ,name='dashboard'),
    path('update_profile/<pk>',NewProfile.as_view() ,name='update_profile'),
]

core/urls.py
from django.urls import path
from .views import AboutView,ContactView,HomeView,NewsView


app_name = 'core'

urlpatterns = [
    path('',HomeView.as_view() ,name='home'),
    path('news/',NewsView.as_view() ,name='news'),
    path('about/',AboutView.as_view() ,name='about'),
    path('contact/',ContactView.as_view() ,name='contact'),
]

nasims/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include
from django.conf.urls.static import static


if settings.DEBUG:
    urlpatterns = [
        path('admin/', admin.site.urls),
        path('',include('account.urls')),
        path('',include('core.urls'))
        ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

education = (
    ('NURSERY','NURSERY'),
    ('PRIMARY','PRIMARY'),
    ('SECONDARY','SECONDARY'),
    ('DEGREE','DEGREE'),
    ('MASTERS','MASTERS'),
    ('PHD','PHD')
)

ids = (
    ('NATIONAL IDENTITY CARD','NATIONAL IDENTITY CARD'),
    ('VOTERS CARD','VOTERS CARD'),
    ('DRIVERS LICENCE','DRIVERS LICENCE'),
    ('PASSPORT','PASSPORT')
)


class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    slug = models.SlugField(max_length=20,null=True,default='')
    other_names = models.CharField(max_length=20,null=True)
    profile_pics = models.ImageField(default='',upload_to='pics',null=True)
    phone_number = models.IntegerField(null=True)
    date_of_birth = models.DateField(null=True)
    gendre = models.CharField(max_length=10,choices=(('MALE','MALE'),('FEMALE','FEMALE')),null=True)
    state_of_origin = models.CharField(max_length=20,null=True)
    lga_origin = models.CharField(max_length=100,null=True)
    scheme_name = models.CharField(max_length=100,null=True)
    year_of_application = models.CharField(max_length=4,null=True)
    residencial_address = models.CharField(max_length=100,null=True)
    state_of_residence = models.CharField(max_length=20,null=True)
    lga_residence = models.CharField(max_length=100,null=True)
    highest_level_of_education = models.CharField(max_length=20,choices=education,null=True)
    id_type = models.CharField(max_length=100,choices=ids,null=True)
    id_number = models.IntegerField(null=True)
    id_image = models.ImageField(upload_to='pics',null=True)
    bvn = models.IntegerField(null=True)
    bank_account_number = models.IntegerField(null=True)
    bank_name = models.CharField(max_length=50,null=True)
    account_name = models.CharField(max_length=50,null=True)
  

    def __str__(self) -> str:
        return f'{self.user}'

core/models.py
from django.db import models

# Create your models here.

account/forms.py
from django.forms import ModelForm
from .models import Profile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name','last_name','username','email','password1','password2',)

class NewProfileForm(ModelForm):
    class Meta:
        model = Profile
        exclude = ('user',)
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        #fields = ('username','email','password1','password2',)

account/views.py
from .models import Profile
from django.urls import reverse
from .forms import RegisterForm,NewProfileForm
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin 
from django.views.generic import TemplateView,CreateView,UpdateView


# Create your views here.

class LoginView(LoginView):
    template_name = 'login.html'

class UserRegistration(CreateView):
    template_name = 'register.html'
    form_class = RegisterForm
    success_url= '/login'


class DashboardView(LoginRequiredMixin,TemplateView):
    template_name = 'dashboard.html'
    login_url = '/login'

class NewProfile(SuccessMessageMixin,UpdateView):
    template_name = 'new_profile.html'
    form_class = NewProfileForm
    model = Profile
    success_message = 'Profile updated successfully'
    success_url= '/dashboard'

        
    
   

core/views.py
from django.views.generic import TemplateView

# Create your views here.


class HomeView(TemplateView):
    template_name ='index.html'
    
class NewsView(TemplateView):
    template_name = 'news.html'

class AboutView(TemplateView):
    template_name = 'about.html'

class ContactView(TemplateView):
    template_name = 'contact.html'

templates/about.html
{% extends 'layout.html' %}

<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>About</title>
  </head>
  <body>
    {% block content %}

    <img name="slide" src="" alt="" />

    {% endblock %}

    <!-- javascript -->
    {% block js %}
    <script src="{% static 'js/about.js' %}"></script>
    {% endblock %}
  </body>
</html>

templates/contact.html
{% extends 'layout.html' %}
<!-- staticfiles -->
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  </head>
  <body>
    <!-- ------------- -->
    {% block content %}
    <div id="carouselExampleIndicators" class="carousel slide">
      <div class="carousel-indicators">
        <button
          type="button"
          data-bs-target="#carouselExampleIndicators"
          data-bs-slide-to="0"
          class="active"
          aria-current="true"
          aria-label="Slide 1"
        ></button>
        <button
          type="button"
          data-bs-target="#carouselExampleIndicators"
          data-bs-slide-to="1"
          aria-label="Slide 2"
        ></button>
        <button
          type="button"
          data-bs-target="#carouselExampleIndicators"
          data-bs-slide-to="2"
          aria-label="Slide 3"
        ></button>
      </div>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <div class="d-flex" style="background-color: #f2fcf9">
            <div
              class="d-none d-md-block w-100 py-4"
              style="padding-left: 100px; padding-right: 100px"
            >
              <img
                src="{% static 'images/nasims-logo.webp' %}"
                alt=""
                srcset=""
                height="150"
                width="150"
                class="p-4"
              />
              <h4 class="text-decoration-underline">Welcome to the</h4>
              <h2>
                National Social <br />
                Investment Management <br />
                System (NASIMS) Portal
              </h2>
              <p>
                The National Social Investment Management System (NASIMS)
                <br />
                is the central management platform for the administration
                <br />
                and coordination of Social Investment Programmes under <br />
                the Federal Ministry of Humanitarian Affairs, Disaster <br />
                Management and Social Development. <br />
                <a href="" class="text-success"> Read More</a>
              </p>
            </div>
            <img
              src="{% static 'images/hero-image3.webp' %}"
              class="d-block w-100"
              alt="..."
            />
          </div>
        </div>

        <div class="carousel-item">
          <div class="d-flex" style="background-color: #f2fcf9">
            <div
              class="d-none d-md-block w-100 py-4"
              style="padding-left: 100px; padding-right: 100px"
            >
              <img
                src="{% static 'images/nasims-logo.webp' %}"
                alt=""
                srcset=""
                height="150"
                width="150"
                class="p-4"
              />
              <h4 class="text-decoration-underline">Welcome to the</h4>
              <h2>
                National Social <br />
                Investment Management <br />
                System (NASIMS) Portal
              </h2>
              <p>
                The National Social Investment Management System (NASIMS)
                <br />
                is the central management platform for the administration
                <br />
                and coordination of Social Investment Programmes under <br />
                the Federal Ministry of Humanitarian Affairs, Disaster <br />
                Management and Social Development. <br />
                <a href="" class="text-success"> Read More</a>
              </p>
            </div>
            <img
              src="{% static 'images/hero-image2.webp' %}"
              class="d-block w-100"
              alt="..."
            />
          </div>
        </div>

        <div class="carousel-item">
          <div class="d-flex" style="background-color: #f2fcf9">
            <div
              class="d-none d-md-block w-100 py-4"
              style="padding-left: 100px; padding-right: 100px"
            >
              <img
                src="{% static 'images/nasims-logo.webp' %}"
                alt=""
                srcset=""
                height="150"
                width="150"
                class="p-4"
              />
              <h4 class="text-decoration-underline">Welcome to the</h4>
              <h2>
                National Social <br />
                Investment Management <br />
                System (NASIMS) Portal
              </h2>
              <p>
                The National Social Investment Management System (NASIMS)
                <br />
                is the central management platform for the administration
                <br />
                and coordination of Social Investment Programmes under <br />
                the Federal Ministry of Humanitarian Affairs, Disaster <br />
                Management and Social Development. <br />
                <a href="" class="text-success"> Read More</a>
              </p>
            </div>
            <img
              src="{% static 'images/hero-image1.webp' %}"
              class="d-block w-100"
              alt="..."
            />
          </div>
        </div>
      </div>
      <button
        class="carousel-control-prev"
        type="button"
        data-bs-target="#carouselExampleIndicators"
        data-bs-slide="prev"
      >
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button
        class="carousel-control-next"
        type="button"
        data-bs-target="#carouselExampleIndicators"
        data-bs-slide="next"
      >
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>

    <!-- -------------- -->
    <div class="bg-dark p-2 text-center">
      <p class="text-light">
        Read more about our response to the Covid-19 pandemic
      </p>
      <a href="" class="text-success">here</a>
    </div>
    <!-- ---------------- -->

    <!-- hero 2 start -->
    <div class="d-block d-md-flex py-3">
      <div class="w-100 text-center">
        <img src="{% static 'images/Group1.webp' %}" alt="" class="w-75" />
      </div>
      <div class="text-center text-md-start w-100 mt-4">
        <h4 class="mt-4">
          Welcome to the National Social Investment Management System (NASIMS)
        </h4>
        <p class="mt-4">
          <a href="" class="text-success"
            >The Federal Ministry of Humanitarian Affairs, Disaster Management
            and Social Development</a
          >
          was established on Wednesday August 21st, 2019 by an Executive
          pronouncement by the President and Commander in Chief of the Armed
          Forces of Nigeria, H.E., Muhammadu Buhari GCFR at the inauguration of
          Ministers for the Federal Republic of Nigeria. Under My leadership as
          Minister, the Ministry will position itself in light of the prevailing
          Humanitarian situation in the country through its Vision, Mission and
          Core values to promote Human dignity and Integration of basic Humane
          benevolence and compassion in the treatment of all Nigerians
        </p>
        <p class="">Sadiya Umar Farouq <br />Honorable Minister</p>
      </div>
    </div>
    <!-- hero 2 end -->

    <!-- hero 3 start -->
    <div class="d-flex flex-md-row flex-column-reverse py-4 mt-4">
      <div class="w-100 p-4">
        <h5 class="">About us</h5>
        <h4 class="">
          Providing efficient, effective, and coordinated humanitarian response
          to Nigerians.
        </h4>
        <p class="">
          The National Social Investment Program of Nigeria is a social welfare
          initiative created by the Federal government of Nigeria in 2015 under
          the direction of the National Social Investment Office. The Program
          was created to ensure a more equitable distribution of resources to
          vulnerable populations, including children, youth, and women. Under
          President Muhammadu Buhari the office has created four programs to
          address poverty and help increase economic development.
        </p>
        <button class="btn btn-success">Read More</button>
      </div>
      <div class="w-100 text-center">
        <img src="{% static 'images/about-img.webp' %}" alt="" class="" />
      </div>
    </div>
    <!-- hero 3 end -->

    <!-- card carousel -->
    <div id="carouselExample" class="carousel slide">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <div class="d-flex">
            <div class="card card-body border-danger m-2">
              (A) first slider card
            </div>
            <div class="card card-body border-danger m-2 d-none d-md-block">
              (A) second slider card
            </div>
          </div>
        </div>
        <div class="carousel-item">
          <div class="d-flex" style="background-color: #f2fcf9">
            <div class="card card-body border-danger m-2 d-none d-md-block">
              (B) first slider card
            </div>
            <div class="card card-body border-danger m-2">
              (B) second slider card
            </div>
          </div>
        </div>

        <div class="carousel-item">
          <div class="d-flex" style="background-color: #f2fcf9">
            <div class="card card-body border-danger m-2 d-none d-md-block">
              (C) first slider card
            </div>
            <div class="card card-body border-danger m-2">
              (C) second slider card
            </div>
          </div>
        </div>

        <div class="carousel-item">
          <div class="d-flex" style="background-color: #f2fcf9">
            <div class="card card-body border-danger m-2 d-none d-md-block">
              (D) first slider card
            </div>
            <div class="card card-body border-danger m-2">
              (D) second slider card
            </div>
          </div>
        </div>
      </div>
      <button
        class="carousel-control-prev"
        type="button"
        data-bs-target="#carouselExample"
        data-bs-slide="prev"
      >
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button
        class="carousel-control-next"
        type="button"
        data-bs-target="#carouselExample"
        data-bs-slide="next"
      >
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
    <!-- card end -->
    <!-- hero 3 start -->

    <!-- hero 3 end -->

    {% endblock %}
  </body>
</html>

templates/dashboard.html
{% extends 'layout.html' %}

<!-- block begining -->
{% block content %}

<div class="mt-4">
  {% for message in messages %}
  <!-- forloop  -->
  {% if message %}
  <div class="alert alert-success mx-auto col-10 col-md-5">{{message}}</div>
  {% endif %}
  <!-- end for loop -->
  {% endfor %}
  <div class="d-flex justify-content-between mx-4">
    <h3>Personal Details</h3>
    <a href="{% url 'account:update_profile' request.user.profile.id %}"
      >Edit</a
    >
  </div>
  <div class="d-flex flex-md-row flex-column-reverse">
    <div
      class="card card-body border-danger mx-auto mx-md-4 mt-2 col-10 col-md-9"
    >
      <div>
        <span>Surname</span>
        <h4>{{request.user.last_name}}</h4>
      </div>

      <div>
        <span>Other Names</span>
        <h4>{{request.user.profile.other_names}}</h4>
      </div>
    </div>
    <div
      class="card card-body text-center mt-2 mx-auto mx-md-4 border-danger col-10 col-md-3"
    >
      <img class="rounded-circle mx-auto" height="100" width="100" alt="" />

      <h3>{{request.user.first_name}} {{request.user.last_name}}</h3>
      <p class="text-secondary">
        <strong>{{request.user.email}}</strong><br />
      </p>

      <strong>NPWR/2020/003511353</strong><br />
      <p><strong>N-Tech - NPR</strong></p>
      <h5>
        <span class="badge rounded-pill bg-success">Shortlisted</span>
      </h5>
      <strong>N-Power Batch C</strong>
    </div>
  </div>
</div>

<div>
  <div>
    <div>
      <div>
        <div>
          <p>Other Names</p>
          <h3>{{request.user.profile.other_names}}</h3>
        </div>

        <div>
          <p>First Name</p>
          <h3>{{request.user.first_name}}</h3>
        </div>

        <div>
          <p>Date of Birth</p>
          <h3>{{request.user.profile.date_of_birth}}</h3>
        </div>

        <div>
          <p>Gendre</p>
          <h3>{{request.user.profile.gendre}}</h3>
        </div>

        <div>
          <p>Phone Number</p>
          <h3>{{request.user.profile.phone_number}}</h3>
        </div>

        <div>
          <p>State of Origin</p>
          <h3>{{request.user.profile.state_of_origin}}</h3>
        </div>

        <div>
          <p>Local Government of Origin</p>
          <h3>{{request.user.profile.lga_origin}}</h3>
        </div>

        <div>
          <p>Scheme Name</p>
          <h3>{{request.user.profile.scheme_name}}</h3>
        </div>

        <div>
          <p>Year of Application</p>
          <h3>{{request.user.profile.year_of_application}}</h3>
        </div>

        <h1>Residential Details</h1>

        <div>
          <p>Residential Address</p>
          <h3>{{request.user.profile.residencial_address}}</h3>
        </div>

        <div>
          <p>State Of Residence</p>
          <h3>{{request.user.profile.state_of_residence}}</h3>
        </div>

        <div>
          <p>Local Government of residence</p>
          <h3>{{request.user.profile.lga_residence}}</h3>
        </div>

        <div>
          <p>Highest Level of Education</p>
          <h3>{{request.user.profile.highest_level_of_education}}</h3>
        </div>

        <div>
          <p>Year of Graduation</p>
          <h3></h3>
        </div>
      </div>
      <!-- hhhhhhhhhhhhhhhhhhhh -->
      <div>
        <div>
          <p>ID Type</p>
          <h3>{{request.user.profile.id_type}}</h3>
        </div>

        <div>
          <p>ID Number</p>
          <h3>{{request.user.profile.id_number}}</h3>
        </div>

        <div>
          <p>Uploaded ID Card</p>
          <img width="100" height="100" alt="" srcset="" />
        </div>

        <div>
          <p>BVN Validity</p>
          <h3>{{request.user.profile.bvn}}</h3>
        </div>

        <h1>Bank Details</h1>

        <div>
          <p>Account Number</p>
          <h3>{{request.user.profile.bank_account_number}}</h3>
        </div>

        <div>
          <p>Bank</p>
          <h3>{{request.user.profile.bank_name}}</h3>
        </div>

        <div>
          <p>Account Name</p>
          <h3>{{request.user.profile.account_name}}</h3>
        </div>
      </div>
    </div>
    <div>
      <img height="100" width="100" alt="profile.png" />
      <div>
        <h3>{{request.user.first_name}} {{request.user.last_name}}</h3>
        <span>{{request.user.email}}</span>
        <p>NPWR/2020/005511535</p>
        <p>N-Tech-NPR</p>
        <span>Shortlisted</span>
        <p>N-Power Batch C</p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/delete_profile.html
<form method="post">
  {% csrf_token %}
  <!-- uuuuuuuu -->
  {{profile}}
  <button type="submit" class="btn btn-danger">Delete</button>
</form>

templates/header.html
{% load static %}

<nav
  style="z-index: 1"
  class="top-0 position-fixed py-4 px-2 top-0 navbar border-bottom bg-light navbar-expand-lg navbar-light w-100"
>
  <a href="" class="navbar-brand d-block d-md-none">LOGO</a>
  <h5 class="d-none d-md-block">
    Federal Ministry of Humanitarian Affairs, Disaster <br />
    Management and Social Development
  </h5>
  <button
    class="navbar-toggler"
    data-bs-toggle="collapse"
    data-bs-target="#navCollapse"
    aria-controls="navCollapse"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navCollapse">
    <ul
      class="d-flex navbar-nav align-items-center justify-content-center ms-auto"
    >
      {% if not request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'core:home' %}">Home</a>
      </li>
      <li class="nav-item"><a class="nav-link" href="">News</a></li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'account:register' %}">Register</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'core:about' %}">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'core:contact' %}">Contact</a>
      </li>

      <li class="nav-item">
        <a
          class="btn btn-success py-3"
          href="{% url 'account:login' %}"
          style="width: 14rem"
          >Login</a
        >
        {% else %}
        <div class="dropdown">
          <a
            class="dropdown-toggle"
            type="button"
            id="dropdownToggle"
            data-bs-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="false"
          >
            <img
              height="50"
              width="50"
              class="rounded-circle"
              src="{{request.user.profile.profile_pics.url}}"
              alt=""
              srcset=""
          /></a>

          <div
            class="dropdown-menu dropdown-menu-left"
            style="margin-left: -100px"
            aria-labelledby="dropdownToggle"
          >
            <a class="dropdown-item" href="{% url 'account:dashboard' %}"
              >Back To Dashboard</a
            >
            <a class="dropdown-item" href="{% url 'account:logout' %}"
              >Sign Out</a
            >
          </div>
        </div>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="{% static 'bootstrap/css/bootstrap.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'bootstrap-icons/bootstrap-icons.css' %}"
    />
    <!-- default styles -->
    {% block style %}
    <link rel="stylesheet" href="{% static 'css/header.css' %}" />
    <link rel="stylesheet" href="{% static 'css/index.css' %}" />
    <link rel="stylesheet" href="{% static 'css/layout.css' %}" />
    {% endblock %}
    <!-- title -->
    {% block title %} {% endblock %}
  </head>
  <body>
    <!-- header section -->
    {% block header %} {% include 'header.html' %} {% endblock %}

    <!-- content section -->
    <div style="margin-top: 105px">{% block content %} {% endblock %}</div>

    <!-- footer section -->
    {% block footer %} {% endblock %}
    <!-- js -->
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    {% block js %} {% endblock %}
  </body>
</html>

templates/login.html
{% extends 'layout.html' %}
<!-- static -->
{% load static %}
<!-- crispy -->
{% load crispy_forms_tags %}

<!-- body -->
{% block content %}
<form
  action=""
  method="post"
  class="col-10 col-md-5 mx-auto"
  style="margin-top: 150px"
>
  {% csrf_token %} {{form|crispy}}

  <button class="btn btn-success w-25">Login</button>
</form>
{% endblock %}

templates/new_profile.html
{% extends 'layout.html' %}
<!-- staticfiles -->
{% load static %}
<!-- crispy -->
{% load crispy_forms_tags %}

<!-- ------------- -->
{% block content %}
<form class="col-10 col-md-7 mx-auto" method="post">
  <h3 class="mt-4 text-decoration-underline">Update Profile</h3>
  {% csrf_token %}
  <!-- form -->
  {{form|crispy}}
  <button class="mb-4 btn btn-success">Create Profile</button>
</form>
{% endblock %}

templates/news.html
Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia dignissimos
expedita distinctio laudantium tempora vero tenetur perspiciatis quod officiis
sit in laboriosam, praesentium porro. Odit nobis consectetur hic. Optio, ex.

templates/register.html
{% extends 'layout.html' %}
<!-- staticfiles -->
{% load static %}
<!-- crispy -->
{% load crispy_forms_tags %}

<!-- ------------- -->
{% block content %}

<div class="col-10 col-md-5 mx-auto mt-4">
  <h3 class="text-decoration-underline">Register to apply</h3>
  <form method="post" class="mt-4">
    {% csrf_token %}

    <!-- form -->
    {{form|crispy}}

    <button class="btn btn-success mb-4" type="submit">Register</button>
  </form>
</div>
{% endblock %}